apiVersion: v1
kind: Service
metadata:
  labels:
    app: customer-ms
  name: customer-ms
  namespace: t31-k8s-observability
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: customer-ms
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: irs-ms
  name: irs-ms-service
  namespace: t31-k8s-observability
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: irs-ms
  type: ClusterIP