<?xml version="1.0" encoding="utf-8" ?>
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                  xmlns:tns="http://dae.msoft.edu/ws/TermsService"
                  xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                  xmlns:xs="http://www.w3.org/2001/XMLSchema"
                  name="TermsEndpointService" targetNamespace="http://dae.msoft.edu/ws/TermsService">

    <wsdl:message name="GetTermRequest">
        <wsdl:part name="term" type="xs:string"/>
    </wsdl:message>

    <wsdl:message name="GetTermResponse">
        <wsdl:part name="value" type="xs:string"/>
    </wsdl:message>

    <wsdl:portType name="TermsEndpoint">
        <wsdl:operation name="GetTerm">
            <wsdl:input message="tns:GetTermRequest"/>
            <wsdl:output message="tns:GetTermResponse"/>
        </wsdl:operation>
    </wsdl:portType>

    <wsdl:binding name="TermsEndpointServiceSoapBinding" type="tns:TermsEndpoint">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="GetTerm">
            <soap:operation soapAction="http://dae.msoft.edu/ws/TermsService/GetTerm"/>
            <wsdl:input name="GetTermRequest">
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output name="GetTermResponse">
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>

</wsdl:definitions>